### ISSUE TITLE
Alignment & non-printable chars

### ISSUE THREAD

**Issue by jaraddowning** [ebwinters/CoronaTracker#7]
I'm getting some non-printable characters in the output. 

```
Here are the latest Corona Virus stats in Switzerland, courtesy of Worldometers:
╔[3╤m=╤39m[╤7m==========================================================╗
║ Cases       │ Deaths      │ Death Rate    │ Recovered     ║
╟[3┼m─┼39m[┼7m──────────────────────────────────────────────────────────╢
║ 7474        │ 98          │ 1.31%         │ 131           ║
╚[3╧m═╧39m[╧7m══════════════════════════════════════════════════════════╝
```
I've tested it on a new install & an one that has just about every font I've ever come across. Thanks for the good work, it's very handy.

Also on nodejs v12, I don't get graphs but that may be something with my system.

**Comment by ebwinters** [comment]
Thanks for opening this, other people have had this problem as well. As for graphs, run an npm update for coronatrack. I've been integrating new features in tandem with the API the CLI uses. 

As for the table, I'll look into that

**Comment by ebwinters** [comment]
once 2bba237 is published then it will appear normal

**Comment by jaraddowning** [comment]
Sorry for bugging you about this. I discovered a lot about colors on the command line with this issue. Always good to learn new things.

**Comment by ebwinters** [comment]
you're not bugging me haha, this is an open source project. Were you able to come up with a better looking fix on your end?

**Comment by jaraddowning** [comment]
The main reason I took an interest in your project was the data, to put it in my i3status bar. I was just testing out the graphs and playing around with it to show off to my wife & kids, they are the only people I get to see right now. It's working great now btw. :+1:

**Comment by ebwinters** [comment]
good to hear! I have to fix some things with the backend API, some functionality was depreciated, so graphs for states will be going away with the next up date. Sorry - they made breaking changes to the API I'm a developer on...
